WARNING 2019-03-19 11:07:34,804 log Not Found: /
WARNING 2019-03-19 11:07:38,599 log Not Found: /favicon.ico
WARNING 2019-03-19 11:07:53,646 log Not Found: /api/ticket/sender/test
ERROR 2019-03-19 11:08:13,469 log Internal Server Error: /api/ticket/send/test/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view ticket.ticket_view.send_email.test_sender_email didn't return an HttpResponse object. It returned None instead.
WARNING 2019-03-19 11:10:38,771 log Not Found: /uploads/image/default.png
WARNING 2019-03-19 11:10:46,340 log Not Found: /uploads/image/default.png
WARNING 2019-03-19 11:10:52,271 log Not Found: /uploads/image/default.png
ERROR 2019-03-19 13:20:32,412 log Internal Server Error: /api/ticket/send/test/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhang/Documents/Python/PESCM/ticket/ticket_view/send_email.py", line 55, in test_sender_email
    print('=======tickets' + tickets.count())
TypeError: must be str, not int
ERROR 2019-03-19 13:21:49,710 log Internal Server Error: /api/ticket/send/test/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhang/Documents/Python/PESCM/ticket/ticket_view/send_email.py", line 67, in test_sender_email
    print('=======tickets_confirm' + tickets_confirm.count())
TypeError: must be str, not int
WARNING 2019-03-19 13:24:31,614 log Not Found: /uploads/image/default.png
WARNING 2019-03-19 13:24:38,908 log Not Found: /uploads/image/default.png
